# Generated by Django 3.2.5 on 2022-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('short_deks', models.TextField()),
                ('long_deks', models.TextField()),
                ('cover_homepage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('img_feature', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_post',
            },
        ),
    ]
